### ISSUE TITLE
[Proposal] Improve metric lookup performance

### ISSUE THREAD

**Issue by mbell697** [pkittenis/graphite-influxdb#13]
We've been using `graphite-influxdb` for awhile and it's been great, the one area where we've had issues is in metric lookup performance. I've been using `varnish` both in front of `graphite-api` and between `graphite-api` and `influxdb` with moderate success, the same is true with my testing of the `memcached` support. I should note that we may be a little unique as we're push a large number of metrics: 200,480 separate metrics the last time I pulled it and we'll probably quadruple that number in the coming months.  

Using a cache between `graphite-api` and `influxdb` greatly improves dashboard rendering due to larging cutting out the need to lookup the metrics needed, but doesn't work well on the user side, metrics are very slow to load in the grafana query editor. This seems largely due to how `graphite-api` looks up metrics, e.g. a request to lookup `statsite.*` where `statsite` is the root of most of our metrics loads a huge amount of data to filter down to only a few branches after that segment. 

Using a cache between `graphite-api` and `grafana-server` solves this issue but doesn't help metric rendering time.

I'd like to propose a different approach to avoid needing to have all these caches around. I'd like your thoughts on this and I've built a prototype of the data structure with some benchmarks here: https://gist.github.com/mbell697/f1d4c9a01a8617e5b50b The prototype is in Ruby as Python isn't my go to language for quick mockups but I can rewrite it in Python if this seems like a sane approach. The benchmarks are with a tree loaded with 200,480 metric names. 

The general idea is to load all metric names periodically and store them into a k-ary tree, then traverse the tree on lookup. In practice I'd start a worker thread in the graphite-api/graphite-influxdb process that would 'refresh' this tree periodically, every 30 minutes or some other configurable value. 

I think the performance of this approach will fix both issues.  Even with a fairly complex graphite glob expression as in the last benchmark I get ~2.36k lookups per second with 200,480 metrics in the tree. 

The code isn't optimized for performance much at the moment. There are also other interesting avenues for future improvement. e.g. store expiration times in the nodes of the tree and check those on lookup, then execute queries in the background to refresh just a portion of the tree rather than doing the periodic bulk update.

Thoughts?

**Comment by pkittenis** [comment]
Hello,

Thank you for the detailed write up - have separately come to a similar conclusion.

Let me try to explain what I have found and you can share your experience as well.

In our setup, we now have:

Graphite API/Graphite-Influxdb -> Varnish -> influxdb API

Graphite-influxdb also has memcached caching all influxdb data, including series list.

The reason for varnish in front of influxdb instead of graphite api is because `/render` requests from Grafana are POST which cannot be cached.

The memcached integration provides both series names and series data caching. The former has a configurable TTL as per configuration details on the main page.

As you alluded, yes, a query to `metrics/find?query=*` will be very slow with large number of series, something we are also running into.

However, with memcached caching series list, after the first call to influxdb series list is stored and served entirely from memcache and is very fast in my testing. As fast as you can get from in memory caching :)

Had also come to the same conclusion, that series list needs periodic loading in order to maintain a cached series list entirely in memory and not have to hit influxdb at all for it.

The reason this should go in memcached and not in-process graphite-api caching is because the graphite-api webapp spawns multiple (and recycles old ones) processes, each with their own cache, which will result in slow performance again. Memcached is shared, does not get reset when webapp restarts, and can be used by multiple graphite-api processes.

Once the full series list is cached, queries for part of nodes, eg `statsite.something.other.*` are always satisfied from the cached full series list. No need to store parts of the tree separately when the whole tree is cached already.

That said, the real solution to this would be to add pagination to series list as returned by influxdb. The reason getting series list is so slow is because with very large lists influxdb is entirely CPU bound on serialisation of the series list into json and said serialiser scales poorly as data increases.

Haven't got around to raising that as a feature request on influxdb yet, or going in and trying to add it myself.

I do aim to have periodic loading of series list in memcached via graphite-influxdb in the final `0.5.1` release.

Does that make sense from what you have found as well?

Would still recommend a cache be used in front of influxdb API though, mainly to protect the DB from multiple identical requests (multiple users looking at same dashboard), which would otherwise have to hit the DB separately, assuming they are not in memcached already.

**Comment by pkittenis** [comment]
Have you tested `memcached` with max value length increased btw?

By default, memcached only lets you store 1MB data value per key, which is not large enough to store large influxdb series lists. If you are still seeing slow metric queries with memcached enabled, that would be why.

Need to set `-I<size>` on memcached options to override, where `<size>` is value in MB. `-I 15` works well for me.

**Comment by mbell697** [comment]
Been on vacation for a few days, sorry for the late response. 

The problem I've seen with caching is that a query for metric names such as '*', which is what grafana generates at the 'first level' of the query builder ends up pulling all series names from Influx. Even when caching the Influx response, it doesn't change the response time much in our setup. In our case the response to such a query is a ~30MB slug of JSON with ~200k series names in it which are later filtered by `find_nodes`. 

I think the fundamental issue is that there is no way that I can dream up to query influx for only unique 'partial series' names that match a regex, i.e. no way to query for `*` and only get `toplevel1.`, `toplevel2.`. 

One possible memcached based solution to this is to cache the result of `find_nodes` instead of `get_series` as I believe it's this loop that has to reduce 200k series into 3 in our case: https://github.com/pkittenis/graphite-influxdb/blob/master/graphite_influxdb/classes/finder.py#L189

**Comment by pkittenis** [comment]
Yup, that is correct, a `*` graphite API query will query influxdb for all series and then reduce them down to top level Graphite style hierarchical top-of-the-tree nodes.

The overwhelming wait time for a `*` query is response time from InfluxDB and in particular serialisation of series list into json. Short of changing InfluxDB API to either (a) allow for hierarchical Graphite style queries or (b) add pagination to series list, influxdb response time will not be changing.

(a) is possible with [graphite templates](https://github.com/influxdb/influxdb/blob/master/services/graphite/README.md#multiple-measurement-matching) which split graphite's hierarchical data into influxdb tags, however, this breaks backwards compatibility with existing dashboards and decreases influxdb performance as it has to regex match on the fly for every metric inserted.

That said, yes `find_nodes` is using regex to reduce the list, which can be slow for very large lists. Will add memcache caching on that as well for next version.

If you turn on debug logging and your memcache settings allow for series list to be cached, you should see the following in `graphite_influxdb` log file:

```
[DEBUG] 2015-12-08 15:38:43,337 - finder.find_nodes() - find_nodes() query <FindQuery: * from * until *>
```

Are you able to test (a) at all? If the template parsing works, performance wise, for large series lists and heavy volume, I'd be keen to add template support in `graphite-influxdb` so that becomes an option.

What `graphite-influxdb` would need for (a) is to allow templates as configured in influxdb to be configured for graphite-influxdb and the plugin would also have to regex match and split a query for, example, `target=stats.my_host.cpu.usage` into `select cpu.usage from graphite where host='my_host' and prefix='stats'`.

**Comment by mbell697** [comment]
> The overwhelming wait time for a * query is response time from InfluxDB and in particular serialisation of series list into json.

The vast majority of time in our setup for a `*` query is spent in `graphite-api` / `graphite-influxdb`. I'm currently caching queries for `show series` with Varnish but actually didn't see a significant difference for the `*` queries coming from InfluxDB directly, it's a bit slower, but not much. Caching the `show series` queries with Varnish does significantly improve dashboard rendering time as we have a lot of wildcard series in our graphs and the aggregate of all these queries hitting Influx does slow it down. I haven't been able to test the memcached approach as this issue is blocking it's use for most of our stuff: https://github.com/pkittenis/graphite-influxdb/issues/11

> Are you able to test (a) at all?

Not at the moment, we're doing some renaming of metrics soon to more strictly follow a `<key>.<value>.<key>.<value>....` pattern to allow this in the future. 

> That said, yes find_nodes is using regex to reduce the list, which can be slow for very large lists. Will add memcache caching on that as well for next version.

I think this will fix most of our issues based on some simple profiling of the code during `*` queries, thanks!

**Comment by pkittenis** [comment]
| The vast majority of time in our setup for a * query is spent in graphite-api / graphite-influxdb

Not the case from our own testing. Below is two `*` queries, first one uncached served from influxdb, second one served from memcached cached influxdb response. Cached query is 5 sec, uncached times out after 1 min.

Yes, the `graphite-influxdb` overhead is 5sec which is high. Still, it is less than 10% of overall uncached query time. This is with ~30k total series, with 200k this would be even more pronounced.

![show_series_respo](https://cloud.githubusercontent.com/assets/1391208/11683632/fc2ea104-9e63-11e5-9a23-2f49512c478d.png)

Of course response time is seen as coming from graphite-influxdb as that's what makes the influxdb query. That does not necessarily mean all or most of the overhead is in graphite-influxdb.

**Comment by pkittenis** [comment]
Closing this - have raised #14 for the agreed on work needed.
